# Project information
site_name: photonai_conformal
repo_name: 'photonai_conformal'
repo_url: 'https://github.com/wwu-mmll/photonai_conformal'
edit_uri: 'edit/master/docs'


# Social media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/wwu_mmll'

# Theme configuration
theme: 
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
  font: false
  features:
     - toc.integrate

# Latex
extra_javascript:
  - assets/javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# extensions
markdown_extensions:
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite
  - admonition
  - pymdownx.details

# Site structure
nav: 
  - Home: "index.md"
  - API:
      - ConformalClassifier: "api/ConformalClassifier.md"
      - ConformalRegressor: "api/ConformalRegressor.md"
  - Examples:
      - DummyTransformer: "examples/ConformalRegressor/ConformalRegressorExample.ipynb"

extra_css:
  - assets/stylesheets/material.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_source: false
  - mkdocs-jupyter:
      execute: True
